spring.application.name=demo_spring_boot
server.port=9090

# MySQL Database Configuration
 #spring.datasource.url=jdbc:mysql://localhost:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
 #spring.datasource.username=root
 #spring.datasource.password=root

# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# Postgres Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/demo_spring_boot
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect